apiVersion: apps/v1
kind: Deployment
metadata:
  name: workout-management-service
  labels:
    app: workout-management-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: workout-management-service
  template:
    metadata:
      labels:
        app: workout-management-service
    spec:
      containers:
        - name: workout-management-service
          image: ghcr.io/77jennifer77/workout-management-service:436e92c48017ccaff39b656c683caa37a4810f08
          ports:
            - containerPort: 1323
