apiVersion: apps/v1
kind: Deployment
metadata:
  name: workout-management-service
  labels:
    app: workout-management-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: workout-management-service
  template:
    metadata:
      labels:
        app: workout-management-service
    spec:
      containers:
        - name: workout-management-service
          image: ghcr.io/77jennifer77/workout-management-service:8266cad88ae3a0595fbf6cf84f5133fa8a039e2b
          ports:
            - containerPort: 1323
